CC = clang
CFLAGS = -Wall -Wextra -Werror

all: Colleen Grace Sully

Colleen: Colleen.c
Grace: Grace.c
Sully: Sully.c

clean:
	$(RM) Colleen
	$(RM) Grace
	$(RM) Sully

re: clean all

-include tests.mk

.PHONY: all clean re
